# Generated by Django 5.2.1 on 2025-12-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellapp', '0003_alter_schedule_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('AUTO_RING', 'Automatic Ring'), ('MANUAL_RING', 'Manual Ring'), ('SCHEDULE_ADD', 'Schedule Added'), ('SCHEDULE_EDIT', 'Schedule Edited'), ('SCHEDULE_DELETE', 'Schedule Deleted')], max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
